# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forgetpass.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from qmessagebox import Ui_Qmessagebox
from database import DB_Users
from verify import Ui_Verify
import smtplib
from random import randrange
import senderdetail


class Ui_ForgetPassword(object):
    """
    GUI For update password or Forgot password
    """
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 10, 791, 91))
        self.label.setStyleSheet("font: 48pt \"FrankRuehl\";\n"
"color: rgb(0, 206, 206);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(80, 140, 631, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.emailId = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.emailId.setFont(font)
        self.emailId.setText("")
        self.emailId.setObjectName("emailId")
        self.horizontalLayout.addWidget(self.emailId)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(80, 229, 631, 51))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.newPassword = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.newPassword.setFont(font)
        self.newPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.newPassword.setObjectName("newPassword")
        self.horizontalLayout_2.addWidget(self.newPassword)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(80, 320, 631, 51))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.confnewPassword = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.confnewPassword.setFont(font)
        self.confnewPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.confnewPassword.setObjectName("confnewPassword")
        self.horizontalLayout_3.addWidget(self.confnewPassword)
        self.changePassword = QtWidgets.QPushButton(self.centralwidget)
        self.changePassword.setGeometry(QtCore.QRect(430, 430, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.changePassword.setFont(font)
        self.changePassword.setObjectName("changePassword")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.changePassword.clicked.connect(lambda: self.changepassword(MainWindow))

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Change Password"))
        self.label_2.setText(_translate("MainWindow", "Email :- "))
        self.emailId.setPlaceholderText(_translate("MainWindow", "Email"))
        self.label_3.setText(_translate("MainWindow", "New Password :- "))
        self.newPassword.setPlaceholderText(_translate("MainWindow", "New Password"))
        self.label_4.setText(_translate("MainWindow", "Conform New Password :- "))
        self.confnewPassword.setPlaceholderText(_translate("MainWindow", "Re-enter New Password"))
        self.changePassword.setText(_translate("MainWindow", "Change Password"))

    def changepassword(self, MainWindow):
        if self.emailId.text():
            if self.newPassword.text():
                if self.newPassword.text() == self.confnewPassword.text():
                    email = self.emailId.text()
                    ck_email = DB_Users().fetchPassword(email)
                    if ck_email is None:
                        Ui_Qmessagebox().qmessagebox("Password", "No account with the entered Email !!")
                    else:
                        newpassword = self.newPassword.text()
                        self.verifyotp(email, newpassword, MainWindow)
                else:
                    Ui_Qmessagebox().qmessagebox("Password", "Password is Not same.")
            else:
                Ui_Qmessagebox().qmessagebox("Password", "Please Enter New Password")
        else:
            Ui_Qmessagebox().qmessagebox("Email", "Please Enter Email ID")

    def select_random(self):
        rand_all = ''
        for i in range(6):
            rand_one = randrange(10)
            rand_all += str(rand_one)
        return rand_all

    def verifyotp(self, email, newpassword, MainWindow):
        try:
            obj = smtplib.SMTP("smtp.gmail.com", 587)
            obj.starttls()
            obj.login(senderdetail.EMAIL, senderdetail.PASSWORD)
            subject = "Verify OTP"
            sent_otp = self.select_random()
            body = f"OTP for make new Password is \n{sent_otp}"
            message = f"Subject:{subject}\n\n{body}"
            obj.sendmail(senderdetail.EMAIL, [email], message)
            obj.quit()
            self.openverify(sent_otp, newpassword, MainWindow)
        except:
            Ui_Qmessagebox().qmessagebox("Network", "May be your device is not connected to Network. Please Check your Network connection.")

    def openverify(self, sent_otp, newpassword, MainWindow):
        self.window = QtWidgets.QMainWindow()
        self.window.setFixedSize(500, 400)
        self.ui = Ui_Verify(sent_otp, signupwindow = MainWindow, password=newpassword)
        self.ui.setupUi(self.window)
        self.window.show()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_ForgetPassword()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
