# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from database import DB_Users
from signup import Ui_SignUp
from qmessagebox import Ui_Qmessagebox
from detail import Ui_Detail
from forgetpass import Ui_ForgetPassword


class Ui_LogIn(QtWidgets.QMainWindow):
    """
    GUI for Log In
    """
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(250, 100, 291, 100))
        self.label.setStyleSheet("font: 35pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(202, 202, 202);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(70, 270, 661, 291))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("FrankRuehl")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(99, 255, 216);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.groupBox_2 = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("FrankRuehl")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet("border-color: rgb(255, 170, 127);")
        self.groupBox_2.setObjectName("groupBox_2")
        self.emailId = QtWidgets.QLineEdit(self.groupBox_2)
        self.emailId.setGeometry(QtCore.QRect(50, 40, 521, 35))
        font = QtGui.QFont()
        font.setFamily("FrankRuehl")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.emailId.setFont(font)
        self.emailId.setText("")
        self.emailId.setObjectName("emailId")
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("FrankRuehl")
        font.setPointSize(16)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.password = QtWidgets.QLineEdit(self.groupBox)
        self.password.setGeometry(QtCore.QRect(50, 40, 521, 35))
        font = QtGui.QFont()
        font.setFamily("FrankRuehl")
        font.setPointSize(12)
        self.password.setFont(font)
        self.password.setText("")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(69, 649, 661, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.signUp = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.signUp.setFont(font)
        self.signUp.setObjectName("signUp")
        self.horizontalLayout.addWidget(self.signUp)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.logIn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.logIn.setFont(font)
        self.logIn.setObjectName("logIn")
        self.horizontalLayout.addWidget(self.logIn)
        self.forgetPassword = QtWidgets.QPushButton(self.centralwidget)
        self.forgetPassword.setGeometry(QtCore.QRect(550, 590, 181, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.forgetPassword.setFont(font)
        self.forgetPassword.setStyleSheet("QPushButton{\n"
"    border-radius: 10px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(143, 143, 143);\n"
"}\n"
"")
        self.forgetPassword.setObjectName("forgetPassword")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.logIn.clicked.connect(self.login)
        self.signUp.clicked.connect(self.signup)
        self.forgetPassword.clicked.connect(self.forgetpassword)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Log In"))
        self.label.setText(_translate("MainWindow", "E-MARS"))
        self.label_2.setText(_translate("MainWindow", "Log In"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Email"))
        self.emailId.setPlaceholderText(_translate("MainWindow", "Email"))
        self.groupBox.setTitle(_translate("MainWindow", "Password"))
        self.password.setPlaceholderText(_translate("MainWindow", "Password"))
        self.signUp.setText(_translate("MainWindow", "Create Account"))
        self.logIn.setText(_translate("MainWindow", "LOGIN"))
        self.forgetPassword.setText(_translate("MainWindow", "Forgot Password?"))

    def signup(self):
        self.window = QtWidgets.QMainWindow()
        self.window.setFixedSize(800, 800)
        self.ui = Ui_SignUp()
        self.ui.setupUi(self.window)
      #  MainWindow.hide()
        self.window.show()

    def login(self):
        if self.emailId.text():
            if self.password.text():
                email = self.emailId.text()
                pword = self.password.text()
                db_pass = DB_Users().fetchPassword(email)
                if db_pass is None:
                    Ui_Qmessagebox().qmessagebox('Email', "Don't have account with this Gmail !!")
                elif pword != db_pass:
                    Ui_Qmessagebox().qmessagebox('Password', "Password is not Correct !!")
                else:
                    self.window = QtWidgets.QMainWindow()
                    self.ui = Ui_Detail(email)
                    self.ui.setupUi(self.window)
                    MainWindow.hide()
                    self.window.show()
            else:
                Ui_Qmessagebox().qmessagebox('Password', "Please enter Password !!")
        else:
            Ui_Qmessagebox().qmessagebox('Email', "Please enter Email !!")

    def forgetpassword(self):
        self.window = QtWidgets.QMainWindow()
        self.window.setFixedSize(800, 600)
        self.ui = Ui_ForgetPassword()
        self.ui.setupUi(self.window)
        self.window.show()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    MainWindow.setFixedSize(800, 800)
    ui = Ui_LogIn()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
