# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'verify.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from qmessagebox import Ui_Qmessagebox
from database import DB_Users

class Ui_Verify(object):
    """
    GUI for verify email.
    Verify OTP sent to email
    """
    def __init__(self,
                 sent_otp,
                 email = None,
                 password = None,
                 datetime = None,
                 firstname = None,
                 lastname = None,
                 dateofbirth = None,
                 imagefile = None,
                 middlename = None,
                 signupwindow = None):
        self.sent_otp = sent_otp
        self.email = email
        self.password = password
        self.datetime = datetime
        self.firstname = firstname
        self.lastname = lastname
        self.dateofbirth = dateofbirth
        self.imagefile = imagefile
        self.middlename = middlename
        self.signupwindow = signupwindow

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 400)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 19, 491, 61))
        self.label.setStyleSheet("font: 34pt \"FrankRuehl\";\n"
"color: rgb(0, 179, 179);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 99, 471, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(40, 189, 411, 71))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.otpInput = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.otpInput.setFont(font)
        self.otpInput.setObjectName("otpInput")
        self.horizontalLayout.addWidget(self.otpInput)
        self.verifyOtp = QtWidgets.QPushButton(self.centralwidget)
        self.verifyOtp.setGeometry(QtCore.QRect(150, 292, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.verifyOtp.setFont(font)
        self.verifyOtp.setObjectName("verifyOtp")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.verifyOtp.clicked.connect(lambda: self.conformotp(MainWindow))

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Verify Email"))
        self.label_2.setText(_translate("MainWindow", "OTP has been sent to your Email. Please Enter OTP here."))
        self.label_3.setText(_translate("MainWindow", "Enter OTP :- "))
        self.otpInput.setPlaceholderText(_translate("MainWindow", "OTP"))
        self.verifyOtp.setText(_translate("MainWindow", "Verify"))

    def conformotp(self, MainWindow):
        if self.sent_otp == self.otpInput.text():
            Ui_Qmessagebox().qmessagebox("OTP Verified", "Otp verified")
            MainWindow.close()
            if self.datetime is None:
                ck_email = DB_Users().updatePassword(self.email, self.password)
                if ck_email:
                    Ui_Qmessagebox().qmessagebox("Password", "Password has been changed Successfully !!")
                else:
                    Ui_Qmessagebox().qmessagebox("Password", "No account with the entered Email")
            else:
                self.insert_into_db()
                Ui_Qmessagebox().qmessagebox("Sign Up", "Account Created Successfully !!")
            self.signupwindow.close()
        else:
            Ui_Qmessagebox().qmessagebox("OTP Not Verified", "Wrong OTP !!")

    def insert_into_db(self):
        db = DB_Users()
        db.insertData(self.email,
                      self.password,
                      self.datetime,
                      self.firstname,
                      self.lastname,
                      self.dateofbirth,
                      self.imagefile,
                      middleName=self.middlename)



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Verify()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
